/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_wasabithumb_jwebview_except_WebViewExceptionImpl */

#ifndef _Included_io_github_wasabithumb_jwebview_except_WebViewExceptionImpl
#define _Included_io_github_wasabithumb_jwebview_except_WebViewExceptionImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_serialVersionUID
#define io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_serialVersionUID -3042686055658047285LL
#undef io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_serialVersionUID
#define io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_serialVersionUID -3387516993124229948LL
#undef io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_serialVersionUID
#define io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_serialVersionUID -7034897190745766939LL
/*
 * Class:     io_github_wasabithumb_jwebview_except_WebViewExceptionImpl
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_wasabithumb_jwebview_except_WebViewExceptionImpl_strerror
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
