/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_wasabithumb_jwebview_JWebViewImpl */

#ifndef _Included_io_github_wasabithumb_jwebview_JWebViewImpl
#define _Included_io_github_wasabithumb_jwebview_JWebViewImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_wasabithumb_jwebview_JWebViewImpl
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_wasabithumb_jwebview_JWebViewImpl_version
  (JNIEnv *, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_JWebViewImpl
 * Method:    create0
 * Signature: (ZLjava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_io_github_wasabithumb_jwebview_JWebViewImpl_create0
  (JNIEnv *, jobject, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
