/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_wasabithumb_jwebview_JWebViewProviderImpl */

#ifndef _Included_io_github_wasabithumb_jwebview_JWebViewProviderImpl
#define _Included_io_github_wasabithumb_jwebview_JWebViewProviderImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_wasabithumb_jwebview_JWebViewProviderImpl
 * Method:    setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_wasabithumb_jwebview_JWebViewProviderImpl_setup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
