/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_wasabithumb_jwebview_WebViewImpl */

#ifndef _Included_io_github_wasabithumb_jwebview_WebViewImpl
#define _Included_io_github_wasabithumb_jwebview_WebViewImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    run0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_run0
  (JNIEnv *, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    terminate0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_terminate0
  (JNIEnv *, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    dispatch0
 * Signature: (Lio/github/wasabithumb/jwebview/param/DispatchCallback;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_dispatch0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    setTitle0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_setTitle0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    setSize0
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_setSize0
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    navigate0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_navigate0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    setHtml0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_setHtml0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    init0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_init0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    eval0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_eval0
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    bindDataSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_bindDataSize
  (JNIEnv *, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    bind0
 * Signature: (Ljava/lang/String;Lio/github/wasabithumb/jwebview/param/BindCallback;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_bind0
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    unbind0
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_unbind0
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     io_github_wasabithumb_jwebview_WebViewImpl
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_wasabithumb_jwebview_WebViewImpl_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
